# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Страница исследований
    url: tour
    weight: 10
  - name: О проекте
    url: post
    weight: 20
  - name: Заключение
    url: event
    weight: 30
  - name: О нас
    url: contact
    weight: 40